version: "3.8"

services:
  db:
    image: mysql:5.7.30
    container_name: gallery-db
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gallerydb
      MYSQL_USER: galleryadmin
      MYSQL_PASSWORD: password
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - "3308:3306"
    restart: on-failure
    volumes: 
      - "./data:/var/lib/mysql"
  api:
    build: ../gallery-api
    container_name: gallery-api
    environment:
      MODE: "prod"
      DB_URL: "galleryadmin:password@tcp(db:3306)/gallerydb?parseTime=true"
      HMAC_KEY: "secret"
    restart: always
    volumes:
      - "./upload:/app/upload"
    depends_on: 
      - db
    links:
      - db
  web:
    build: ../gallery
    container_name: gallery-web
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - api
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    
    

    